In [1]:

import json

with open('conversion_numeric.json', 'r') as f:
    conversion_numeric = json.load(f)

inverted_conversion_numeric = {v: k for k, v in conversion_numeric.items()}

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/API_SP.POP.TOTL_DS2_en_csv_v2_84031.csv', index_col=0)
df.head()

,Country Code,Indicator Name,Indicator Code,2000,2001,2002,2003,2004,2005,2006,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,"Population, total",SP.POP.TOTL,89101.0,90691.0,91781.0,92701.0,93540.0,94483.0,95606.0,...,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0,NaN
Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,401600588.0,412001885.0,422741118.0,433807484.0,445281555.0,457153837.0,469508516.0,...,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0,NaN
Afghanistan,AFG,"Population, total",SP.POP.TOTL,19542982.0,19688632.0,21000256.0,22645130.0,23553551.0,24411191.0,25442944.0,...,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0,NaN
Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,269611898.0,277160097.0,284952322.0,292977949.0,301265247.0,309824829.0,318601484.0,...,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0,NaN
Angola,AGO,"Population, total",SP.POP.TOTL,16394062.0,16941587.0,17516139.0,18124342.0,18771125.0,19450959.0,20162340.0,...,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0,NaN

In [14]:
country_code_to_values = {}
for index, row in df.iterrows():
    country_code = row['Country Code']
    year_range = [str(year) for year in range(2000, 2021)]
    values = [row[year] for year in year_range]
    country_code_to_values[country_code] = values

In [15]:
country_code_to_values['ABW']

[89101.0,
 90691.0,
 91781.0,
 92701.0,
 93540.0,
 94483.0,
 95606.0,
 96787.0,
 97996.0,
 99212.0,
 100341.0,
 101288.0,
 102112.0,
 102880.0,
 103594.0,
 104257.0,
 104874.0,
 105439.0,
 105962.0,
 106442.0,
 106585.0]

In [20]:
population_dataset = {}
for country_code, values in country_code_to_values.items():
    new_key = inverted_conversion_numeric.get(country_code, None)
    if new_key is not None:
        population_dataset[new_key] = values
    else:
        print(f"Key for country code '{country_code}' not found in inverted_conversion_numeric.")

Key for country code 'AFE' not found in inverted_conversion_numeric.
Key for country code 'AFW' not found in inverted_conversion_numeric.
Key for country code 'ARB' not found in inverted_conversion_numeric.
Key for country code 'CEB' not found in inverted_conversion_numeric.
Key for country code 'CHI' not found in inverted_conversion_numeric.
Key for country code 'CSS' not found in inverted_conversion_numeric.
Key for country code 'EAP' not found in inverted_conversion_numeric.
Key for country code 'EAR' not found in inverted_conversion_numeric.
Key for country code 'EAS' not found in inverted_conversion_numeric.
Key for country code 'ECA' not found in inverted_conversion_numeric.
Key for country code 'ECS' not found in inverted_conversion_numeric.
Key for country code 'EMU' not found in inverted_conversion_numeric.
Key for country code 'EUU' not found in inverted_conversion_numeric.
Key for country code 'FCS' not found in inverted_conversion_numeric.
Key for country code 'HIC' not found in inverted_conversion_numeric.
Key for country code 'HPC' not found in inverted_conversion_numeric.
Key for country code 'IBD' not found in inverted_conversion_numeric.
Key for country code 'IBT' not found in inverted_conversion_numeric.
Key for country code 'IDA' not found in inverted_conversion_numeric.
Key for country code 'IDB' not found in inverted_conversion_numeric.
Key for country code 'IDX' not found in inverted_conversion_numeric.
Key for country code 'INX' not found in inverted_conversion_numeric.
Key for country code 'LAC' not found in inverted_conversion_numeric.
Key for country code 'LCN' not found in inverted_conversion_numeric.
Key for country code 'LDC' not found in inverted_conversion_numeric.
Key for country code 'LIC' not found in inverted_conversion_numeric.
Key for country code 'LMC' not found in inverted_conversion_numeric.
Key for country code 'LMY' not found in inverted_conversion_numeric.
Key for country code 'LTE' not found in inverted_conversion_numeric.
Key for country code 'MEA' not found in inverted_conversion_numeric.
Key for country code 'MIC' not found in inverted_conversion_numeric.
Key for country code 'MNA' not found in inverted_conversion_numeric.
Key for country code 'NAC' not found in inverted_conversion_numeric.
Key for country code 'OED' not found in inverted_conversion_numeric.
Key for country code 'OSS' not found in inverted_conversion_numeric.
Key for country code 'PRE' not found in inverted_conversion_numeric.
Key for country code 'PSS' not found in inverted_conversion_numeric.
Key for country code 'PST' not found in inverted_conversion_numeric.
Key for country code 'SAS' not found in inverted_conversion_numeric.
Key for country code 'SSA' not found in inverted_conversion_numeric.
Key for country code 'SSF' not found in inverted_conversion_numeric.
Key for country code 'SST' not found in inverted_conversion_numeric.
Key for country code 'TEA' not found in inverted_conversion_numeric.
Key for country code 'TEC' not found in inverted_conversion_numeric.
Key for country code 'TLA' not found in inverted_conversion_numeric.
Key for country code 'TMN' not found in inverted_conversion_numeric.
Key for country code 'TSA' not found in inverted_conversion_numeric.
Key for country code 'TSS' not found in inverted_conversion_numeric.
Key for country code 'UMC' not found in inverted_conversion_numeric.
Key for country code 'WLD' not found in inverted_conversion_numeric.

In [22]:

with open('population_dataset.json', 'w') as f:
    json.dump(population_dataset, f)